### ISSUE TITLE
how can i use "visa" dataset

### ISSUE THREAD

**Issue by henrychou1233** [arimousa/DDAD#11]
it's complex to change the code!
can you release a visa one?
please~

**Comment by arimousa** [comment]
You should not modify our code for data preparation. Only, adjust the values listed in config.yaml according to the mentioned values in front of them and the table on the readme file.

You can find how to preprocess the dataset in the following GitHub repo of Amazon.
https://github.com/amazon-science/spot-diff/tree/main
You just need to download the dataset and place it in your project directory. After running the code at https://github.com/amazon-science/spot-diff/blob/main/utils/prepare_data.py,
it provides you with the same format as MVTec.

**Comment by henrychou1233** [comment]
Num params:  32952707
/home/anywhere3090l/Desktop/henry/jjvisa/VisA_dataset/
Traceback (most recent call last):
  File "/home/anywhere3090l/Desktop/henry/jjvisa/main.py", line 84, in <module>
    train(args)
  File "/home/anywhere3090l/Desktop/henry/jjvisa/main.py", line 24, in train
    trainer(unet, config.data.category, config)
  File "/home/anywhere3090l/Desktop/henry/jjvisa/train.py", line 28, in trainer
    trainloader = torch.utils.data.DataLoader(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anywhere3090l/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anywhere3090l/miniconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0

以上為我的錯誤資訊

然後新資料好像在visa_pytorch 裡面有一層1cls資料夾 然後才是dataset 裡面確實與mvtec一樣
這樣我要怎麼設定config呢

以下為我目前的設定
data :
  name: VisA  #MVTec #MTD #VisA 
  data_dir: /home/anywhere3090l/Desktop/henry/jjvisa/VisA_dataset/  #MVTec #VisA #MTD  
  category: candle   #['carpet', 'bottle', 'hazelnut', 'leather', 'cable', 'capsule', 'grid', 'pill', 'transistor', 'metal_nut', 'screw','toothbrush', 'zipper', 'tile', 'wood']    
                   # ['candle', 'capsules', 'cashew', 'chewinggum', 'fryum', 'macaroni1', 'macaroni2', 'pcb1', 'pcb2' ,'pcb3', 'pcb4', 'pipe_fryum']
  image_size: 256
  batch_size: 8
  mask : True 
  imput_channel : 3



model:
  checkpoint_dir: /home/anywhere3090l/Desktop/henry/jjvisa/checkpoints/VisA   #MTD  #MVTec  #VisA
  checkpoint_name: weights
  exp_name: default
  feature_extractor: densenet121 # wide_resnet50_2 #resnet50
  learning_rate: 3e-4 
  weight_decay: 0.05
  epochs: 3
  load_chp : 1750 # From this epoch checkpoint will be loaded. Every 250 epochs a checkpoint is saved. Try to load 750 or 1000 epochs for Visa and 1000-1500-2000 for MVTec.
  DA_epochs: 3  # Number of epochs for Domain adaptation. Try [0-3]. "Fine tuninig this parameter results in better performance".
  eta : 1 # Stochasticity parameter for denoising process.
  v : 7 # Control parameter for pixel-wise and feature-wise comparison. v * D_p + D_f
  w : 4 # Conditionig parameter. The higher the value, the more the model is conditioned on the target image. "Fine tuninig this parameter results in better performance".
  w_DA : 3 # Conditionig parameter for domain adaptation. The higher the value, the more the model is conditioned on the target image.
  trajectory_steps: 1000
  test_trajectoy_steps: 200   # Starting point for denoining trajectory.
  test_trajectoy_steps_DA: 200  # Starting point for denoining trajectory for domain adaptation.
  skip : 20   # Number of steps to skip for denoising trajectory.
  skip_DA : 20
  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 32
  seed : 42



metrics:
  image_level_AUROC: True
  pixel_level_AUROC: True
  pro: True

**Comment by arimousa** [comment]
It appears that the data directory is not configured properly. Have you renamed 'visa_pytorch' to 'VisA'? Additionally, in the config file, you set data_dir as /home/anywhere3090l/Desktop/henry/jjvisa/VisA_dataset/. If the folder name is 'VisA,' you should modify it to data_dir: /home/anywhere3090l/Desktop/henry/jjvisa/VisA.

It seems that the data has been correctly preprocessed, but it should be located in the correct directory. While this shouldn't affect data loading, it's worth noting that you're not using the latest version of our code. The updated version corresponding to our recent publication can be found at: https://arxiv.org/abs/2305.15956.

**Comment by henrychou1233** [comment]
data :
  name: VisA  #MVTec #MTD #VisA 
  data_dir: /home/anywhere3090l/Desktop/henry/henryddadvisa/VisA/  #MVTec #VisA #MTD  
  category: candle  #['carpet', 'bottle', 'hazelnut', 'leather', 'cable', 'capsule', 'grid', 'pill', 'transistor', 'metal_nut', 'screw','toothbrush', 'zipper', 'tile', 'wood']    
                   # ['candle', 'capsules', 'cashew', 'chewinggum', 'fryum', 'macaroni1', 'macaroni2', 'pcb1', 'pcb2' ,'pcb3', 'pcb4', 'pipe_fryum']
  image_size: 256 
  batch_size: 32 # 32 for DDAD and 16 for DDADS
  DA_batch_size: 16 #16 for MVTec and [macaroni2, pcb1] in VisA, and 32 for other categories in VisA
  test_batch_size: 16 #16 for MVTec, 32 for VisA
  mask : True 
  imput_channel : 3



model:
  DDADS: False
  checkpoint_dir: /home/anywhere3090l/Desktop/henry/henryddadvisa/checkpoints/VisA   #MTD  #MVTec  #VisA
  checkpoint_name: weights
  exp_name: default
  feature_extractor: wide_resnet101_2 #wide_resnet101_2  # wide_resnet50_2 #resnet50
  learning_rate: 3e-4 
  weight_decay: 0.05
  epochs: 3
  load_chp : 1500 # From this epoch checkpoint will be loaded. Every 250 epochs a checkpoint is saved. Try to load 750 or 1000 epochs for Visa and 1000-1500-2000 for MVTec.
  DA_epochs: 30 # Number of epochs for Domain adaptation.
  DA_chp: 8
  v : 1 #7 # 1 for MVTec and cashew in VisA, and 7 for VisA (1.5 for cashew). Control parameter for pixel-wise and feature-wise comparison. v * D_p + D_f
  w : 8 # Conditionig parameter. The higher the value, the more the model is conditioned on the target image. "Fine tuninig this parameter results in better performance".
  w_DA : 3 #3 # Conditionig parameter for domain adaptation. The higher the value, the more the model is conditioned on the target image.
  DLlambda : 0.1 # 0.1 for MVTec and 0.01 for VisA
  trajectory_steps: 1000
  test_trajectoy_steps: 250   # Starting point for denoining trajectory.
  test_trajectoy_steps_DA: 250  # Starting point for denoining trajectory for domain adaptation.
  skip : 25   # Number of steps to skip for denoising trajectory.
  skip_DA : 25
  eta : 1 # Stochasticity parameter for denoising process.
  beta_start : 0.0001
  beta_end : 0.02 
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 2
  seed : 42



metrics:
  auroc: True
  pro: True
  misclassifications: False
  visualisation: False
還是不行ㄟ 以上是我的config visa已用mvtec的包法
仍會顯示以下
(base) anywhere3090l@3090l:~/Desktop/henry/henryddadvisa$ python main.py --train True
Class:  candle    w: 8    v: 1    load_chp: 1500    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Training...
 Num params:  32952707
Traceback (most recent call last):
  File "/home/anywhere3090l/Desktop/henry/henryddadvisa/main.py", line 88, in <module>
    train(config)
  File "/home/anywhere3090l/Desktop/henry/henryddadvisa/main.py", line 29, in train
    trainer(unet, config.data.category, config)#config.data.category, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anywhere3090l/Desktop/henry/henryddadvisa/train.py", line 27, in trainer
    trainloader = torch.utils.data.DataLoader(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anywhere3090l/miniconda3/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anywhere3090l/miniconda3/lib/python3.11/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
以下為我的檔案資料夾
(base) anywhere3090l@3090l:~/Desktop/henry/henryddadvisa$ ls /home/anywhere3090l/Desktop/henry/henryddadvisa/VisA/candle
ground_truth  test  train
(base) anywhere3090l@3090l:~/Desktop/henry/henryddadvisa$ ls /home/anywhere3090l/Desktop/henry/henryddadvisa
anomaly_map.py        figures          metrics.py         split_csv       VisA_pytorch
checkpoints           images           __pycache__        spot-diff-main  visualize.py
config.yaml           LICENSE          README.md          train.py
dataset.py            LICENSE-DATASET  reconstruction.py  unet.py
ddad.py               loss.py          requirements.txt   utils
feature_extractor.py  main.py          resnet.py          VisA

**Comment by arimousa** [comment]
I guess you should remove / after VisA in data_dir: /home/anywhere3090l/Desktop/henry/henryddadvisa/VisA/
