### ISSUE TITLE
為啥eval那邊沒反應

### ISSUE THREAD

**Issue by henrychou1233** [arimousa/DDAD#13]
(base) anywhere3090l@3090l:~/Desktop/henry/ddadvisa$ python main.py --train True
Class:  pcb4    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Training...
 Num params:  32952707
/home/anywhere3090l/Desktop/henry/ddadvisa/VisA
Epoch 0 | Loss: 196538.21875
(base) anywhere3090l@3090l:~/Desktop/henry/ddadvisa$ python main.py --domain_adaptation True
Class:  pcb4    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Domain Adaptation...
/home/anywhere3090l/Desktop/henry/ddadvisa/VisA
Epoch 0 | Loss: 0.02777327597141266
(base) anywhere3090l@3090l:~/Desktop/henry/ddadvisa$ python main.py --eval True
Class:  pcb4    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16

**Comment by arimousa** [comment]
There is no need to open an issue for follow-up questions. You can simply put your question in the same thread as before. It may take a bit of time for me to answer your question.
It should give you results after some minutes if you have set up every part correctly.
