### ISSUE TITLE
problem about feat0

### ISSUE THREAD

**Issue by TSAAAAA** [arimousa/DDAD#14]
how to save feat0？ Does this mean that fine_tuning is not required in categories with FE_epoch =0?
In code feature_extractor.py the model "feat" is saved from 1.   Does this mean that I should set DA_chp=1?
![image](https://github.com/arimousa/DDAD/assets/83752252/3bda9ce1-f3fb-4234-a290-e96aac7463aa)
I can hardly repeat "carpet"  experiment with w=0, load_chp=2500, and DA_chp=1.
![image](https://github.com/arimousa/DDAD/assets/83752252/f5094810-5452-409c-8807-77547cad25b8)
![image](https://github.com/arimousa/DDAD/assets/83752252/3fe63255-789b-4ace-88e8-245ce42f6d99)
I am curious at what step I went wrong. Looking forward to your reply.

**Comment by arimousa** [comment]
Hi, I fixed the problem in the code. Now feat0 will be saved after running the code. As you correctly said, feat0 means no domain adaptation. You can simply set DA_chp=0.

**Comment by pluto-8** [comment]
你好，FE epochs是指DA_chp还是DA_epochs

**Comment by arimousa** [comment]
DA_epochs is for training and DA_chp is for inference. DA_epochs means for how many epochs you want to train the model. Regarding your question FE epochs refers to DA_chp
