### ISSUE TITLE
Regarding the Execution Results of MVTecAD Bottle Evaluation.

### ISSUE THREAD

**Issue by bulky-kohsakunishida** [arimousa/DDAD#2]
Thank you for sharing such a wonderful piece of work.

I tried executing the evaluation after training MVTecAD bottle on Colab Pro+, and the following log was output:

```
Sample :  0  predicted as:  0  label is:  1 
Sample :  10  predicted as:  0  label is:  1 
Sample :  15  predicted as:  0  label is:  1 
Sample :  49  predicted as:  0  label is:  1 
Sample :  50  predicted as:  0  label is:  1 
Sample :  51  predicted as:  0  label is:  1 
Sample :  52  predicted as:  0  label is:  1 
Sample :  53  predicted as:  0  label is:  1 
Sample :  55  predicted as:  0  label is:  1 
Sample :  58  predicted as:  0  label is:  1 
Sample :  59  predicted as:  0  label is:  1 
Sample :  60  predicted as:  0  label is:  1 
Sample :  61  predicted as:  0  label is:  1 
Sample :  62  predicted as:  0  label is:  1 

AUROC: 1.0
AUROC pixel level: 0.9292386174201965 
PRO: 0.7771466867947617
threshold:  0.15196724
```

The AUROC pixel level result is lower than the value mentioned in the Readme. Upon checking the images in the results, 13 out of 83 seemed to be misclassified.

If there are any specific points or precautions to consider for reproduction, please let me know.
![bottlesample0](https://github.com/arimousa/DDAD/assets/63831582/c4b37e13-9077-443e-9cd9-c57e04ce9662)
![bottlesample0heatmap](https://github.com/arimousa/DDAD/assets/63831582/b38ec582-622f-445e-8930-36f3cb69f86a)

**Comment by arimousa** [comment]
Some hyperparameters in config.yaml should be modified to get the best result. Please tweak DA_epochs and w. Remember after changing DA_epochs you need to fine-tune the feature extractor again. Also, hyperparameter w determines the power of conditioning. Based on the sample you sent it may help if you decrease its value.

**Comment by bulky-kohsakunishida** [comment]
Thank you for your response.
I should conduct fine-tuning according to the following settings mentioned in the paper:

5.2 Experimental Settings
"to w = 3 when fine-tuning the feature extractor"

I will give it a try.
Thank you.
