### ISSUE TITLE
Why nothing happens when running eval

### ISSUE THREAD

**Issue by getmoons** [arimousa/DDAD#21]
~/diffusion/DDAD$ python main.py --eval True
Class:  screw    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16

This seems to be because the --eval is unknown in parse_args()
`def parse_args():
    cmdline_parser = argparse.ArgumentParser('DDAD')    
    cmdline_parser.add_argument('-cfg', '--config', 
                                default= os.path.join(os.path.dirname(os.path.abspath(__file__)),'config.yaml'), 
                                help='config file')
    cmdline_parser.add_argument('--train', 
                                default= False, 
                                help='Train the diffusion model')
    cmdline_parser.add_argument('--detection', 
                                default= False, 
                                help='Detection anomalies')
    cmdline_parser.add_argument('--domain_adaptation', 
                                default= False, 
                                help='Domain adaptation')
    args, unknowns = cmdline_parser.parse_known_args()
    return args`

**Comment by arimousa** [comment]
Sorry for the confusion it should be 
python main.py --detection True

**Comment by getmoons** [comment]
ok, thanks
