### ISSUE TITLE
Question about the initilization of "ch" in UNetModel.__init__()

### ISSUE THREAD

**Issue by sunchengyi** [arimousa/DDAD#22]
I am reading the code about UNetModdel in unet.py.
Lines 278-281 in UNetModel.\_\_init__(): 
> ch = int(channel_mults[0] * base_channels)
> self.down = nn.ModuleList(
>               [TimestepEmbedSequential(nn.Conv2d(self.in_channels, base_channels, 3, padding=1))]
>                )  

That means the number of output channels of the first element in self.down should be "base_channels".
On the other hand, according to lines 288-293, this number should be "ch".
Of course, if channel_mults[0] is 1, it would not cause any probleｍ. But for img_size being 512, channel_mults[0] is 0.5.
I have not run the code to test it. However, I think something might be wrong here.
Shoud be Line 278 modified to be
> ch = int(base_channels)

or channel_mults[0] should be set to be 1 for all of img_size?

**Comment by sunchengyi** [comment]
I ran the code by setting img_size=512. And it resulted in errors. In order to solve it, I have to change channel_mults[0] to be 1.

**Comment by arimousa** [comment]
Thanks. I also uploaded the UNet based on the following repo:
There are some fixed taken place.
https://github.com/openai/guided-diffusion/blob/27c20a8fab9cb472df5d6bdd6c8d11c8f430b924/guided_diffusion/unet.py

**Comment by sunchengyi** [comment]
Thank you!
