### ISSUE TITLE
How to set w_DA in Domain Adaptation?

### ISSUE THREAD

**Issue by sunchengyi** [arimousa/DDAD#24]
I am training models on MVTec AD myself.
How to set w_DA in fine tuning feature extractor?
Should I fix w_DA to be 3 for all of the categories or set w_DA=w with w being best setting for each category?

**Comment by arimousa** [comment]
w_DA is set to 3 for all experiments. However, we are also introducing a new technique for automatic hyperparameter selection to resolve the burden of manual selecting.
We will share the code soon and I will keep you posted.
