### ISSUE TITLE
Question about the precision

### ISSUE THREAD

**Issue by sunchengyi** [arimousa/DDAD#29]
I noticed that in UNetModel.forward(), the data type is explicitly set to be torch.float32.
Is there any reason to do this?
Does it mean that float32 is necessary for UNet and mixed precision is not suitable to the model?

**Comment by arimousa** [comment]
We selected the model from the mentioned repo. However I noticed it is also maintained. 
I concur that making it mixed precision is smarter than float32.

**Comment by sunchengyi** [comment]
Yes, mixed precision is faster.
I just tried and found the training time was reduced about 20%.
Thank you very much!

**Comment by arimousa** [comment]
Great. Then I close the issue.
