### ISSUE TITLE
Request for Fine-Tuning Parameters in MVTec's config.yaml

### ISSUE THREAD

**Issue by hsunchi** [arimousa/DDAD#3]
Hello, thank you for  realease this awesome work.
Regarding the result of the  Mvtec dataset mentioned in the paper, could you please provide some fine-tune parameters such as  'load_chp','DA_epochs','w',and so on?
 I've encountered lower results for certain classes. I think it might be due to my parameter settings.

If it's not possible, that's okay too. Thank you very much.

**Comment by arimousa** [comment]
Hello, we will publish detailed fine-tuned parameters setting soon.

**Comment by hsunchi** [comment]
Thank you very much, I am greatly looking forward to it!

**Comment by hsunchi** [comment]
Hello, I have another quetion, about DDAD-10, does the "10" indicate that run the evaluation 10 times, and select the best one as the result?  I ask this because I couldn't find the correspoding code for this part.

**Comment by hsunchi** [comment]
I see! I misunderstood the meaning in the paper. I'm sorry for the confusion. Thank you for your explanation.
