### ISSUE TITLE
Question in making heat map

### ISSUE THREAD

**Issue by sunchengyi** [arimousa/DDAD#30]
In the function _anomaly_map.heat_map()_, the anomaly map is calculate by combining the feature and pixel distances as follows

>anomaly_map += f_d + config.model.v * (torch.max(f_d)/ torch.max(i_d)) * i_d

Then if *f_d* and *i_d* have more than one samples, *torch.max(f_d)* and *torch.max(i_d)* would give the maximum over all of the samples. Is there something wrong? I think the maximum should be sample-wise. Then it should be 

> anomaly_map += f_d + config.model.v * (torch.amax(f_d, (1,2,3), True)/ torch.amax(i_d, (1,2,3), True)) * i_d

Do I misunderstand it?

**Comment by arimousa** [comment]
Hi, we found it slightly more effective than doing per sample or all samples together. It acts as a normalization over the batch.

**Comment by sunchengyi** [comment]
However, this means that the anomaly map of a sample would depend on other samples in the batch.
And different predictions would be gotten by just changing the test batch size. It does not seem reasonable.
I do not think it is suitable to use something like batch normalization over the test samples in inference.
