### ISSUE TITLE
Invalid  load key

### ISSUE THREAD

**Issue by jobenmar** [arimousa/DDAD#33]
Hi, 
I'm trying to run the code for fine tuning using the command in the Readme.md but I have the following error:

Traceback (most recent call last):
  File "/content/DDAD/main.py", line 91, in <module>
    finetuning(config)
  File "/content/DDAD/main.py", line 46, in finetuning
    checkpoint = torch.load(os.path.join(os.getcwd(), config.model.checkpoint_dir, config.data.category, str(config.model.load_chp)))
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x9e'.

Searching in several places I find that this might be due to corrupted checkpoint files from Google Drive.
Does someone have the same issue?

**Comment by arimousa** [comment]
Firstly, let's confirm the availability of the checkpoints in the "checkpoints/MVTec" folder. If you're not on a Unix-like operating system, the downloaded checkpoints might come with a ".zip" postfix. In that case, you can simply rename them to ".chp". And then, in the "config.yaml" file, you can modify the "load_chp" parameter from "2000" to "2000.chp", for example. This ensures consistency in file extensions and makes the configuration more explicit.

**Comment by jobenmar** [comment]
This worked for the screw samples, but now I'm trying to replicate the results for the rest of categories and I get the following error: ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by arimousa** [comment]
It seems data are not placed in the correct directory. So dataloader cannot load data.
