### ISSUE TITLE
我用UBUNTU 

### ISSUE THREAD

**Issue by henrychou1233** [arimousa/DDAD#39]
但執行Python3 main.py --domain_adaptation True會閃退

**Comment by arimousa** [comment]
Can you send me the error?

**Comment by henrychou1233** [comment]
沒有 他就cmd會自己閃退 但我把adaption epoch設成0就可以跑了 但這樣等於adaption沒用到

**Comment by arimousa** [comment]
The checkpoints might not be loaded correctly. If they are in a zip file, please remove the .zip extension and use only the raw file.
