### ISSUE TITLE
Some questions about the traininig time and the finally results

### ISSUE THREAD

**Issue by Henry0528** [arimousa/DDAD#4]
First thank you for your excellent work, while I met some questions when reproducing the results:
1. I find that the training time is extremely long. I used 3 3090 to train the model on the MVTec dataset and it took me almost 2 days to finish the whole class training process.
2. There is some large gap between the report results and the one I reproduced, like class carpet
AUROC: 0.6737560033798218
AUROC pixel level: 0.8384530544281006 
threshold:  0.59561723
I kept almost all of the parameters unchanged in the config.yaml except for the batchsize, I wonder whether the setting is the same as the one you used and if not , how can I make the proper change to get the similar results.

**Comment by arimousa** [comment]
Training the model on 15 categories of MVTec for 2 days is realistic since diffusion models are expensive to train.
Some hyperparameter tuning is necessary to achieve optimal results as mentioned in the config file and readme. We will soon publish the best settings for each category.

**Comment by Jay-zzcoder** [comment]
I also met this question about the results of carprt, there is a huge gap between the report results and the one I reproduced, I try epochs 1000, 1500, 2000 , AD epoch 1,2 3 and many  hyperparameter

**Comment by arimousa** [comment]
For carpet w = 0 and DA_chp =0 would be the best. However, I will publish checkpoints and settings very soon.

**Comment by Jay-zzcoder** [comment]
> For carpet w = 0 and DA_chp =0 would be the best. However, I will publish checkpoints and settings very soon.

There is likely no AD_chp in config.yaml, you mean DA_epochs or others?

**Comment by Jay-zzcoder** [comment]
> The DA_epochs indicates the number of iterations for fine-tuning the feature extractor. And DA_chp indicates the checkpoint you load the checkpoint. For carpet setting them to zero would results in the best.

AD_chp=0 means I onlt need to train one iteration to fine-tuning the feature extractor for carpet?

**Comment by arimousa** [comment]
It means a pretrained feature extractor outperforms a fine-tuned one.

**Comment by Jay-zzcoder** [comment]
> It means a pretrained feature extractor outperforms a fine-tuned one.

No fine tuning? directly use pretrained feature extractor?

**Comment by arimousa** [comment]
> > It means a pretrained feature extractor outperforms a fine-tuned one.
> 
> No fine tuning? directly use pretrained feature extractor?

Exactly.

**Comment by Jay-zzcoder** [comment]
> > > It means a pretrained feature extractor outperforms a fine-tuned one.
> > 
> > 
> > No fine tuning? directly use pretrained feature extractor?
> 
> Exactly.

I directly use pretrained feature extractor and set w=0, I reproduced the best results is:
Image AUROC: 91.7
Pixel AUROC: 93.9 
PRO: 81.2

**Comment by arimousa** [comment]
checkpoints are published
