### ISSUE TITLE
results

### ISSUE THREAD

**Issue by henrychou1233** [arimousa/DDAD#40]
results資料集是要自己創嗎
因為我跑完 我找不到結果圖
Class:  toothbrush    w: 2    v: 1    load_chp: 2000    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=4
Detecting Anomalies...
AUROC: (88.9,83.4)
/home/anywhere3090l/Desktop/henry/DDAD-main/metrics.py:96: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame({"pro": mean(pros), "fpr": fpr, "threshold": th}, index=[0])], ignore_index=True)
PRO: 48.6

**Comment by arimousa** [comment]
In the config file, you can set the variable visualisation: True. It is the last line of the config.yaml
