### ISSUE TITLE
Question about the training process of VisA Dataset

### ISSUE THREAD

**Issue by AbbeGo** [arimousa/DDAD#42]
I would like to know whether the background of the images was removed during the training and validation process using the VisA dataset., and do you think whether the background is removed or not during the anomaly detection process (training, validation, testing) has a significant impact on the model's performance? Looking forward to your reply.

**Comment by arimousa** [comment]
Hi, I did not incorporate background removal during training or inference, but I can see how it could be useful. I’ve noticed that sometimes background noise, such as dust or similar artifacts, is mistakenly detected as anomalies (spurious anomalies). I believe that implementing background removal could help reduce such false positives and improve the reliability of anomaly detection. It can be done by using SAM.

**Comment by AbbeGo** [comment]
Thank you for your response! I do believe that whether to remove the background during training and testing has a significant impact on the actual performance. Your answer has provided me with a more comprehensive perspective and solutions.
