### ISSUE TITLE
The settings of model and the best results of mvtec

### ISSUE THREAD

**Issue by Jay-zzcoder** [arimousa/DDAD#7]
Could you provide the settings of best results for mvtec. I try many hyperparameters but there is some gap on results of some class in mvtec between my results and results in the paper

**Comment by arimousa** [comment]
Sorry for any inconvenience caused. However, I will upload all the checkpoints and best settings for each category within a week.

**Comment by Jay-zzcoder** [comment]
> Sorry for any inconvenience caused. However, I will upload all the checkpoints and best settings for each category within a week.

Thank you for your reply and this excellent work, I am looking forward to your checkpoints and settings
