### ISSUE TITLE
detection issue using the checkpoints file you provided

### ISSUE THREAD

**Issue by lwtgithublwt** [arimousa/DDAD#9]
Hello, I encountered the following issue while using the checkpoints file you provided for testing. I'm not sure if you can point out the mistake or provide a solution to the problem. Thank you very much

Class:  leather    w: 8    v: 1    load_chp: 2000/data.pkl    feature extractor: wide_resnet101_2          w_DA:  3          DLlambda:  0.1
config.model.test_trajectoy_steps=250 , config.data.test_batch_size=16
Detecting Anomalies...
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    detection(config)
  File "main.py", line 36, in detection
    checkpoint = torch.load(os.path.join(os.getcwd(), config.model.checkpoint_dir, config.data.category, str(config.model.load_chp)))
  File "/home/dell/anaconda3/envs/diffusion2.0/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/dell/anaconda3/envs/diffusion2.0/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by arimousa** [comment]
Hello, I'm uncertain about the origin of the issue. Can you confirm whether you're utilizing Python 3.8 and PyTorch 1.13? Additionally, is this problem specific to the "leather" category or does it happen to other categories as well?

**Comment by lwtgithublwt** [comment]
> Hello, I'm uncertain about the origin of the issue. Can you confirm whether you're utilizing Python 3.8 and PyTorch 1.13? Additionally, is this problem specific to the "leather" category or does it happen to other categories as well?

Thank you for your reply. I did not use pytorch 1.13 because I saw in the requirements file that torch=2.0.1 was written, so I used 2.0.1. However, the checkpoints file I obtained after training myself is usable, and I will try again using 1.13.
